version: '3.9'

services:

  mailhog:
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.mail-http.rule=Host(`mail.traefik.devengine.fr`)
        - traefik.http.routers.mail-http.entrypoints=web
        - traefik.http.routers.mail-http.middlewares=https-redirect
        - traefik.http.routers.mail-https.entrypoints=websecure
        - traefik.http.routers.mail-https.tls=true
        - traefik.http.routers.mail-https.tls.certresolver=leresolver
        - traefik.http.routers.mail-https.rule=Host(`mail.traefik.devengine.fr`)
        - traefik.http.services.mail.loadbalancer.server.port=8025
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
