version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=50M
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.pma-https.entrypoints=websecure
        - traefik.http.routers.pma-https.tls=true
        - traefik.http.routers.pma-https.tls.certresolver=leresolver
        - traefik.http.routers.pma-https.rule=Host(`pma.traefik.nawarelbaya.com`)
        - traefik.http.services.pma.loadbalancer.server.port=80
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-public
      - pma-public

networks:
  traefik-public:
    external: true
  pma-public:
    external: true
